---
title: "Example Analysis using jointCompRisk"
author: "Wenqing Zhang"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
### Part I: CIF Inference

```{r setup, include=FALSE}
library(jointCompRisk)
library(readr)
library(dplyr)
library(survival)
```

```{r}
raw <- read_csv("DUMMY_CH.csv")
long <- read.csv("DUMMY_LONG.csv")
```

```{r}
# 1) Standard CIF:
mydata_std <- prep_data_cif(
  data             = raw,
  ID               = "ID",
  TimeToRecovery   = "TimeToRecovery",
  TimeToDeath      = "TimeToDeath",
  Recov_Censoring  = "RecoveryCensoringIndicator",
  Death_Censoring  = "DeathCensoringIndicator",
  BaselineScore    = "BaselineScore",
  Treatment        = "Treatment"
)


res_std <- do_cif_analysis(mydata_std, tau=29)
res_std$RMGT
res_std$RMLT
res_std$Net
```

```{r}
# Prepare weighted CIF data with updated variable names
prepped_w <- prep_data_weighted_cif(
  data_main = raw,
  data_long = long,

  wID_main              = "ID",
  wTimeToRecovery_main  = "TimeToRecovery",
  wTimeToDeath_main     = "TimeToDeath",
  wRecov_Censoring_main = "RecoveryCensoringIndicator",
  wDeath_Censoring_main = "DeathCensoringIndicator",
  wBaselineScore_main   = "BaselineScore",
  wTreatment_main       = "Treatment",

  wID_long              = "PersonID",
  wADY_long             = "RelativeDay",
  wScore_long           = "OrdinalScore",

  wStates_death         = c(4,5,6,7), 
  wWeights_death        = c(2,1.5,1,0.5),
  wStates_discharge     = c(4,5,6,7),
  wWeights_discharge    = c(0.5,1,1.5,2)
)

# Run Weighted CIF analysis at tau=15
res_w15 <- do_weighted_cif_analysis(prepped_w, tau=15)
res_w15$WRMLT
res_w15$WRMGT

# Run Weighted CIF analysis at tau=29
res_w29 <- do_weighted_cif_analysis(prepped_w, tau=29)
res_w29$WRMLT
res_w29$WRMGT
```

